[dev]
OKTA_ORG=zuora.okta.com
OKTA_AWS_APP_URL=https://zuora.okta.com/home/amazon_aws/0oa1bnkg58zmE2QT11d8/272
AWS_IAM_KEY=
AWS_IAM_SECRET=

[stg]
OKTA_ORG=zuora.okta.com
OKTA_AWS_APP_URL=https://zuora.okta.com/home/amazon_aws/0oaydjetjaICZQTUBKKM/272
AWS_IAM_KEY=
AWS_IAM_SECRET=

[prod]
OKTA_ORG=zuora.okta.com
OKTA_AWS_APP_URL=https://zuora.okta.com/home/amazon_aws/0oa148q1gzxDS3txG1d8/272
AWS_IAM_KEY=
AWS_IAM_SECRET=

[prod_ana]
# Zuora Account: 729633627761
OKTA_ORG=zuora.okta.com
OKTA_AWS_APP_URL=https://zuora.okta.com/home/amazon_aws/0oa1fran82vNhjDSb1d8/272
AWS_IAM_KEY=
AWS_IAM_SECRET=
